const express = require('express');
const router = express.Router();
const { verifyToken, authorize } = require('../middleware/auth');
const ctrl = require('../controllers/invoiceController');
router.use(verifyToken);
router.get('/summary', authorize('SUPER_ADMIN'), ctrl.getFinancialSummary);
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getById);
router.post('/:id/payments', ctrl.addPayment);
module.exports = router;
