const ROLES = { SUPER_ADMIN: 'SUPER_ADMIN', LAB_TECHNICIAN: 'LAB_TECHNICIAN' };

const ORDER_STATUS = { CREATED: 'CREATED', PAID: 'PAID', SAMPLE_PENDING: 'SAMPLE_PENDING', SAMPLE_COLLECTED: 'SAMPLE_COLLECTED', PROCESSING: 'PROCESSING', RESULT_RECEIVED: 'RESULT_RECEIVED', VERIFICATION_PENDING: 'VERIFICATION_PENDING', VERIFIED: 'VERIFIED', REPORT_GENERATED: 'REPORT_GENERATED', COMPLETED: 'COMPLETED', CANCELLED: 'CANCELLED' };

const SAMPLE_STATUS = { PENDING: 'PENDING', COLLECTED: 'COLLECTED', RECEIVED: 'RECEIVED', PROCESSING: 'PROCESSING', COMPLETED: 'COMPLETED', REJECTED: 'REJECTED', CANCELLED: 'CANCELLED' };

const RESULT_FLAG = { NORMAL: 'NORMAL', HIGH: 'HIGH', LOW: 'LOW', CRITICAL: 'CRITICAL', ABNORMAL: 'ABNORMAL' };

const RESULT_STATUS = { PENDING: 'PENDING', REVIEWED: 'REVIEWED', VERIFICATION_PENDING: 'VERIFICATION_PENDING', VERIFIED: 'VERIFIED', REJECTED: 'REJECTED' };

const REPORT_TYPE = { WITH_HEADER: 'WITH_HEADER', WITHOUT_HEADER: 'WITHOUT_HEADER' };

const REPORT_STATUS = { DRAFT: 'DRAFT', GENERATED: 'GENERATED', FINAL: 'FINAL' };

const LIS_RESULT_STATUS = { RECEIVED: 'RECEIVED', MATCHED: 'MATCHED', UNMATCHED: 'UNMATCHED', PROCESSING: 'PROCESSING', VERIFIED: 'VERIFIED', REJECTED: 'REJECTED' };

const PAYMENT_METHOD = { CASH: 'CASH', UPI: 'UPI', CARD: 'CARD', ONLINE: 'ONLINE' };

const INVOICE_STATUS = { PENDING: 'PENDING', PARTIAL: 'PARTIAL', PAID: 'PAID', CANCELLED: 'CANCELLED' };

module.exports = { ROLES, ORDER_STATUS, SAMPLE_STATUS, RESULT_FLAG, RESULT_STATUS, REPORT_TYPE, REPORT_STATUS, LIS_RESULT_STATUS, PAYMENT_METHOD, INVOICE_STATUS };
