import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import api from '../../services/api';

const VerifyReport = () => {
  const { reportId } = useParams();
  const [verificationStatus, setVerificationStatus] = useState('loading'); // 'loading', 'verified', 'not_found', 'error'
  const [reportDetails, setReportDetails] = useState(null);

  useEffect(() => {
    if (reportId) {
      verifyReport();
    }
  }, [reportId]);

  const verifyReport = async () => {
    try {
      const response = await api.get(`/api/verify-report/${reportId}`);
      if (response.data && response.data.verified) {
        setVerificationStatus('verified');
        setReportDetails(response.data.details); // Should not contain PII
      } else {
        setVerificationStatus('not_found');
      }
    } catch (err) {
      if (err.response && err.response.status === 404) {
        setVerificationStatus('not_found');
      } else {
        setVerificationStatus('error');
      }
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <div style={styles.header}>
          <h2>Report Verification</h2>
        </div>
        
        <div style={styles.content}>
          {verificationStatus === 'loading' && (
            <div style={styles.stateContainer}>
              <div style={styles.spinner}></div>
              <p>Verifying report authenticity...</p>
            </div>
          )}

          {verificationStatus === 'verified' && (
            <div style={styles.stateContainer}>
              <div style={styles.iconSuccess}>✓</div>
              <h3 style={styles.titleSuccess}>VERIFIED</h3>
              <p style={styles.message}>This is an authentic report generated by our laboratory.</p>
              
              {reportDetails && (
                <div style={styles.detailsBox}>
                  <p><strong>Report ID:</strong> {reportId}</p>
                  <p><strong>Test Type:</strong> {reportDetails.testName}</p>
                  <p><strong>Issue Date:</strong> {new Date(reportDetails.issuedAt).toLocaleDateString()}</p>
                </div>
              )}
            </div>
          )}

          {verificationStatus === 'not_found' && (
            <div style={styles.stateContainer}>
              <div style={styles.iconError}>✕</div>
              <h3 style={styles.titleError}>NOT FOUND</h3>
              <p style={styles.message}>We could not verify this report. It may be invalid or tampered with.</p>
            </div>
          )}

          {verificationStatus === 'error' && (
            <div style={styles.stateContainer}>
              <div style={styles.iconWarning}>!</div>
              <h3 style={styles.titleWarning}>VERIFICATION FAILED</h3>
              <p style={styles.message}>There was a technical issue while verifying the report. Please try again later.</p>
            </div>
          )}
        </div>

        <div style={styles.footer}>
          <Link to="/" style={styles.link}>Return to Home</Link>
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: '#f4f5f7',
    padding: '20px',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    width: '100%',
    maxWidth: '400px',
    overflow: 'hidden',
  },
  header: {
    backgroundColor: '#f8fafc',
    padding: '20px',
    borderBottom: '1px solid #e2e8f0',
    textAlign: 'center',
  },
  content: {
    padding: '30px 20px',
  },
  stateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  iconSuccess: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: '#c6f6d5',
    color: '#38a169',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '32px',
    fontWeight: 'bold',
    marginBottom: '16px',
  },
  iconError: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: '#fed7d7',
    color: '#e53e3e',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '32px',
    fontWeight: 'bold',
    marginBottom: '16px',
  },
  iconWarning: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: '#feebc8',
    color: '#dd6b20',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '32px',
    fontWeight: 'bold',
    marginBottom: '16px',
  },
  titleSuccess: {
    color: '#38a169',
    margin: '0 0 10px 0',
    fontSize: '24px',
  },
  titleError: {
    color: '#e53e3e',
    margin: '0 0 10px 0',
    fontSize: '24px',
  },
  titleWarning: {
    color: '#dd6b20',
    margin: '0 0 10px 0',
    fontSize: '24px',
  },
  message: {
    color: '#4a5568',
    margin: '0 0 20px 0',
    lineHeight: '1.5',
  },
  detailsBox: {
    backgroundColor: '#f7fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '16px',
    width: '100%',
    textAlign: 'left',
    boxSizing: 'border-box',
  },
  footer: {
    padding: '20px',
    borderTop: '1px solid #e2e8f0',
    textAlign: 'center',
    backgroundColor: '#f8fafc',
  },
  link: {
    color: '#4299e1',
    textDecoration: 'none',
    fontWeight: '500',
  },
  spinner: {
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #3182ce',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    animation: 'spin 1s linear infinite',
    marginBottom: '16px',
  },
};

// Add keyframes for spinner in a global stylesheet or handle inline if possible
const styleSheet = document.createElement("style");
styleSheet.type = "text/css";
styleSheet.innerText = `
@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
`;
document.head.appendChild(styleSheet);

export default VerifyReport;
